### ISSUE TITLE
Mining is not possible since 29.09.2021

### ISSUE THREAD

**Issue by martyartmann** [codemasterPL/tNYCOIN#2]
Hello,

Mining is still not possible on 29.09.2021
But the Status says "Mining up"

**Comment by codemasterPL** [comment]
ping mining.tnycoin.com

Does it work ?

**Comment by codemasterPL** [comment]
dns propagation.

**Comment by martyartmann** [comment]
Yes, the ping works. But my 5 pieces of ESP32 are not displayed at https://tnycoin.com/wa.php (User 75vknjt24ekoso8).
I will try to set up an ESP32 again.

**Comment by codemasterPL** [comment]
Double check  settings on your ESPs, i can't see any miners connecting for this user today.

**Comment by martyartmann** [comment]
I have now tried everything possible, the 0.5 and 0.5.5 version, all ESP32 reset and reinstalled, all ESP32 overwritten 
with "OTA Web Updater" and started all over again. nothing helped, my five miners are no longer running.
They are visible in my WIFI and, according to Wireshark, also send data to the Internet. 
I have no clue whats the cause of this. On Tuesday of this week they all ran smoothly.

sincerly
Marty

**Comment by codemasterPL** [comment]
wireshark showing showing the data is sent where?


telnet mining.tnycoin.com 1911

works ?

**Comment by martyartmann** [comment]
Hello,

wireshark says they send to 92.222.68.46 

Telnet output:

telnet mining.tnycoin.com 1911
Trying 92.222.68.46...
Connected to mining.tnycoin.com.
Escape character is '^]'.
tNYCOIN 0.5 Welcome


my settings all look the same, only the rig name is different

TNYMiner 0.5(5) c44f33114469
(c) razor 2021 - mine cheap!

----------------------------------------------
Network.....: [_Miner]                                          <- my WIFI connection only for the Miners
Network Pass: [ password]                                 <- isn't my real password ;-)
Select Coin.: [tNYCOIN]
Username....: [ 75vknjt24ekoso8]
Rig Name....: [ ESP32-2]                                      <- i have five ESP32 with names from ESP32-0 to ESP-4
Reset Miner.: [_now]
Update miner: [Update]
----------------------------------------------
Core1.......: Connecting to mining server
Core2.......: Connecting to mining server

As I said, the miners worked wonderfully until the https://tnycoin.com/ page was temporarily gone.
I already have a balance of 0.03717 coins

I have just tested what the ESP32 do when I turn off my "Miner" WIFI Net. They will immediately start blinking blue rapidly. When the WIFI Net is back on, it takes another 2-3 minutes until they stop to blink again. The only thing they don't do is mine.

Regards
Marty

**Comment by codemasterPL** [comment]
Here's the test i have performed,

```
tNYCOIN 0.5 Welcome
JOB,75vknjt24ekoso8,ESP32-2,0.5,c44f33114469
c7962caa54569b0c37de3f2c2fae591175817dd4,f3d7c98a4f30269968c509c8cce3c73169c243db,1830
```
Server side looks good, 

Can you connect to this WiFi "Miner" and try to telnet again ?

**Comment by martyartmann** [comment]
Hello,

telnet mining.tnycoin.com 1911
Trying 92.222.68.46...
Connected to mining.tnycoin.com.
Escape character is '^]'.
tNYCOIN 0.5 Welcome

and 
Connection closed by foreign host 
after a few seconds

**Comment by codemasterPL** [comment]
Is this your IP : 188.174.41.182 ?

**Comment by martyartmann** [comment]
Yes it is

**Comment by codemasterPL** [comment]
your telnet connection came through - but your miners are not hitting the server.

check their configuration (wifi?, firewall?)
you can also plug one of them to serial monitor to see what's going on

**Comment by martyartmann** [comment]
I've tried everything possible, 
deleted all ESP32 completely - reloaded the OTA updater - made the update to 0.5.5,
the WIFI network changed several times ( i have 3 different),
one miner connected to my LTE router, 
one miner connected to my smartphone in thetering mode. 
one miner connected to a total different WIFI accesspoint direct LAN connected to my DSL Router
Not a single one connects to the server

As I have already written, all miners worked fine at the beginning of last week 
and I have not changed anything in my network settings.


Here my Serial output:

- Ready to roll
.
.
.
Starting Task.1
Starting Task.0Core.1 Connecting to Server

Core.0 Connecting to Server
Core.1 Failed connecting to server
Core.0 Failed connecting to server
Core.1 Connecting to Server
Core.0 Connecting to Server
Core.1 Failed connecting to server
Core.0 Failed connecting to server

and so on and so on.......



Well, then I'll probably put mining on hold for now.

I will definitely look at the project in a few weeks again.

regards
Marty

**Comment by codemasterPL** [comment]
Just tried to do with 0.5.5 on LTE, and works like charm.


```

21:23:10.250 -> Rig : LTE_TEST
21:23:10.250 -> Coin: 0
21:23:10.250 -> - Entering SETUP Mode
21:23:10.350 -> - Awaiting Setup
21:23:11.379 -> - Ready to roll
21:23:11.412 -> .
21:23:12.408 -> .
21:23:13.405 -> .
21:23:14.402 -> .
21:23:15.398 -> .
21:23:16.394 -> .
21:23:17.424 -> Starting Task.1
21:23:17.424 -> Starting Task.0
21:23:17.424 -> Core.1 Connecting to Server
21:23:17.424 -> Core.0 Connecting to Server
21:23:23.074 -> Core.1 Online - Server version: tNYCOIN 0.5 Welcome
21:23:23.108 -> Core.0 Online - Server version: tNYCOIN 0.5 Welcome
21:23:28.225 -> Core.1 JOB Hash:ce3e565754870d75dc8871567902bb72b168cc5d Expected:40f619ada3bddc28ea0eb44b01e226520a70239c Diff: 48201
21:23:28.225 -> Core.0 JOB Hash:40f619ada3bddc28ea0eb44b01e226520a70239c Expected:d7d341921077513560546124e7def9fa95f851d7 Diff: 48201

```
Check again with this binary:

[0.5.5 reupload](https://easyupload.io/s4csa5)

**Comment by codemasterPL** [comment]
I see you're up now.

`[INF] x.y.41.182(75vknjt24ekoso8) PONG`

Is it with the official release or the bin i have provided above?

**Comment by martyartmann** [comment]
Yes the new
 bin file seems to work

**Comment by codemasterPL** [comment]
Good to see you back online,
i'll close this issue now and reupload bin to release 0.5.5

**Comment by codemasterPL** [comment]
Closing, miners up after reflashing.
