### ISSUE TITLE
Not mining 0.61

### ISSUE THREAD

**Issue by kolesar007** [codemasterPL/tNYCOIN#3]
Hello,

since I update to 0.61 my miners not mining at all.
I notice that Rig name change to "0", but I can not change this?!

Any help to solve this.

BR
Sandi

**Comment by codemasterPL** [comment]
Are you following the latest protocol update ?
https://github.com/codemasterPL/tNYCOIN/blob/main/MINING_PROTOCOL

**Comment by martyartmann** [comment]
@kolesar007 
Are your miners working now?
Mine haven't done anything since the last 0.61 changeover.
If one observes the number of miners (previously around 60 now 0-6) it seems that many miners feel the same way.

greetings
Michael

**Comment by kolesar007** [comment]
No still not working .. stil no my miners showing on site

BR
Sandi

ᐧ

**Comment by codemasterPL** [comment]
Please upgrade to 0.62, https://github.com/codemasterPL/tNYCOIN/releases/tag/v0.62 and let me know if issues resolved.

**Comment by martyartmann** [comment]
Seems to work now, but the coins per day are much less than before. 
Sometimes a captcha does not appear when I register for my wallet, so I cannot register.
I then have to reload the page several times until a capcha appears

greetings 
Michael

**Comment by codemasterPL** [comment]
> Seems to work now, but the coins per day are much less than before. Sometimes a captcha does not appear when I register for my wallet, so I cannot register. I then have to reload the page several times until a capcha appears
> 
> greetings Michael

Thanks for confirming :) 
I'll close the issue as your miners are up, for the captcha, you can raise another one.
